# Generated by Django 2.2.24 on 2022-08-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_post', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='react',
            name='reaction_type',
        ),
        migrations.AlterField(
            model_name='react',
            name='reaction',
            field=models.CharField(choices=[('WOW', 'WOW'), ('LIT', 'LIT'), ('LOVE', 'LOVE'), ('HA', 'HAHA'), ('THUMBS - UP', 'UP'), ('THUMBS - DOWN', 'DOWN'), ('ANGRY', 'ANGRY'), ('SAD', 'SAD')], max_length=100),
        ),
    ]
