# Generated by Django 2.2.24 on 2022-08-24 09:26

from django.db import migrations, models
import fb_post.constants.enum


class Migration(migrations.Migration):

    dependencies = [
        ('fb_post', '0002_auto_20220823_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='reaction',
            field=models.CharField(choices=[(fb_post.constants.enum.ReactionType('WOW'), 'WOW'), (
            fb_post.constants.enum.ReactionType('LIT'), 'LIT'), (fb_post.constants.enum.ReactionType('LOVE'), 'LOVE'), (
                                            fb_post.constants.enum.ReactionType('HAHA'), 'HAHA'), (
                                            fb_post.constants.enum.ReactionType('THUMBS - UP'), 'THUMBS - UP'), (
                                            fb_post.constants.enum.ReactionType('THUMBS - DOWN'), 'THUMBS - DOWN'), (
                                            fb_post.constants.enum.ReactionType('ANGRY'), 'ANGRY'), (
                                            fb_post.constants.enum.ReactionType('SAD'), 'SAD')], max_length=100),
        ),
    ]
