# Generated by Django 2.2.24 on 2022-08-24 17:20

from django.db import migrations, models
import fb_post.constants.enum


class Migration(migrations.Migration):

    dependencies = [
        ('fb_post', '0003_auto_20220824_0926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='react',
            name='reaction',
            field=models.CharField(choices=[('WOW', fb_post.constants.enum.ReactionType('WOW')), ('LIT', fb_post.constants.enum.ReactionType('LIT')), ('LOVE', fb_post.constants.enum.ReactionType('LOVE')), ('HAHA', fb_post.constants.enum.ReactionType('HAHA')), ('THUMBS - UP', fb_post.constants.enum.ReactionType('THUMBS - UP')), ('THUMBS - DOWN', fb_post.constants.enum.ReactionType('THUMBS - DOWN')), ('ANGRY', fb_post.constants.enum.ReactionType('ANGRY')), ('SAD', fb_post.constants.enum.ReactionType('SAD'))], max_length=100),
        ),
    ]
