# Generated by Django 2.2.24 on 2022-08-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fb_post', '0004_auto_20220824_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commented_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='post',
            name='posted_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='react',
            name='reacted_at',
            field=models.DateTimeField(),
        ),
    ]
